### ISSUE TITLE
[1000 BANK] Update token modal 

### ISSUE THREAD

**Issue by wpmonty** [BanklessDAO/bankless-dao-website#49]
The existing token modal does not have a way to disconnect/change wallets. It does not display the full address nor does it allow a one-click "add to metamask".

**Requirements**
Per a new design from Logan, update the existing token modal with the following changes:

1. Change modal title to "BANK Account"
2. Update modal design 
3. Add current account address
4. Add clickable eyeball icon to toggle obfuscation of address
5. Add clickable text to copy address
6. Add external link to the address on Etherscan
7. Add clickable text to change/disconnect wallet (let us know what is possible here)
8. Update BANK section design / copy
9. Fun: On hover, the token icon should play a rotating gif.
9. Add a clickable (/claim) block if the user has claimable funds associated with the account; otherwise do not show.  
10. If connected to MetaMask, show clickable text to "Add token to MetaMask".

Omit: the "Bank Stats" link will be for future iterations

**REWARD: 1000 BANK**

**We can add the primary dev to Figma**

![Screen Shot 2021-05-25 at 8 26 37 PM](https://user-images.githubusercontent.com/7841239/119589067-b2a80800-bd97-11eb-9483-dc7c6dab05e4.png)

**Comment by Oktalize** [comment]
@wpmonty This one sounds fun, count me in!

**Comment by Oktalize** [comment]
Closing this issue, this is now live.
