### ISSUE TITLE
Error: Invariant failed: A root already exists for provided key DEFAULT.

### ISSUE THREAD

**Issue by jonathanprozzi** [BanklessDAO/bankless-dao-website#9]
![bankless-ssr-web3react-error](https://user-images.githubusercontent.com/9438776/117171551-f7441300-ad98-11eb-8fe6-11192bfe3dd7.png)

This error is thrown when using `yarn dev` and seems related to SSR and the client-side context provided by web3react.

There is an open issue in web3react for something similar. I've started working on this and am submitting a pull request -- checking if the code is running client-side or server-side in the `_app.tsx` code seems to resolve this issue.

**Comment by wpmonty** [comment]
Closed with #48
